name: Master CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Custom Job - Made in Malawi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto version
        uses: mitch1009/autoversion@1
        with:
          override: true
      - name: build step
        id: building
        uses: mitch1009/maction@v2 # Very proud of my workflow.
        with:
          who-to-greet: "Ochanza"
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          passcode: ${{secrets.PASSCODE}}
          recipients: '[{"email": "mitch.chanza@gmail.com", "name":"Mitch Chanza"}]'
          message: ${{ github.event.head_commit.message }}
          # upgrades to v2

