name: Master CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Custom Job - Made in Malawi
    steps:
      - name: build step
        id: building
        uses: mitch1009/maction@v0.0.7
        with:
          who-to-greet: "Ochanza"
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          passcode: ${{secrets.PASSCODE}}
          recipients: '[{"to": "mitch.chanza@gmail.com"}]'
          message: ${{ github.event.head_commit.message }},
          subject: "New Aupdates"
          # upgrades
