name: Master CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Custom Job - Made in Malawi
    steps:
      - name: build step
        id: building
        uses: mitch1009/maction@v0.0.3
        with:
          who-to-greet: "Ochanza"
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          passcode: ${{secrets.PASSCODE}}
          message: |
             '[{
             "to": "mitch.chanza@gmail.com"
             }]'
